### ISSUE TITLE
All parameters & body fields are optional

### ISSUE THREAD

**Issue by jall** [grameenfoundation/taroworks-api-docs#4]
Would be nice to be mandatory where possible, e.g.
- response types
- `changeLogNumber`
- `id` when updating
- `form` / `formVersion` for sub-form entities

Looks like there are two ways to do this via `postman-to-openapi`
1. [Tagging the parameters](https://joolfe.github.io/postman-to-openapi/#parameters-parsing) with `[required]` in their description
1. Adding metadata via [markdown table in the request description](https://joolfe.github.io/postman-to-openapi/#pass-meta-information-as-markdown) or as cli options

**Comment by zylina-racette** [comment]
Alright, I hit some limits with postman-to-openapi so I've been manually editing the swagger.yaml file it created. I'll make a ticket to address this, I think all of the API fields are mandatory but we'll double-check.
